Implement a class using posix timer
matsumotory/mruby-timer-thread pull request #2
Opened 2017-03-22 07:10 UTC by udzura

Hi, I have added POSIX timer-based API, using `timer_create(2)` family.

TODOs are:

* [ ] Follow the interfaces of [TimerThread](https://github.com/matsumotory/mruby-timer-thread/pull/1/files#diff-324b691c1cada8f8510e81449b451390R20)
* [ ] Resolve conflict

2017-03-25 06:41 UTC, udzura commented
All done! Usage is as test case: https://github.com/matsumotory/mruby-timer-thread/pull/2/files#diff-50fda337a4df58a689cafe63edf37c9e

2017-03-25 07:17 UTC, matsumotory requested changes

2017-03-25 07:17 UTC, matsumotory commented on test/posix_test.rb
> +      usleep 1000
why counter under 4？

2017-03-25 07:17 UTC, matsumotory commented on test/posix_test.rb
> +    pt.run timer_msec, timer_msec
timer_msec args is duplicated?

2017-03-25 07:17 UTC, matsumotory commented on src/timer_thread.c
> +  struct sigaction sact;
I'd like to support C90.

2017-03-25 07:17 UTC, matsumotory commented on src/timer_thread.c
> +  mrb_value ret = mrb_hash_new_capa(mrb, 2);
I'd like to support C90.

2017-03-25 07:17 UTC, matsumotory commented on src/timer_thread.c
> +    mrb_sys_fail(mrb, "mrb_get_args");
You should use raise when isn't syscall error.

2017-03-25 07:17 UTC, matsumotory commented on src/timer_thread.c
> +  char key[sizeof("__mrb_timer_trap_proc_") + 3];
I'd like to support C90.

2017-03-25 07:19 UTC, matsumotory commented
Also check that you can run multiple timers.

2017-03-25 07:25 UTC, udzura commented on test/posix_test.rb
> +      usleep 1000
`pt.run timer_msec, timer_msec` 's second arg is interval(like libuv's timer).

This checks the count will be incremented 4 times (first invoke + interval invoke x 3)
via L28 - 30's block.

2017-03-25 07:26 UTC, udzura commented
> multiple timers
This means 2 >= timers in the same code? Intervel timer is tested via https://github.com/matsumotory/mruby-timer-thread/pull/2/files#r108030011

2017-03-25 07:26 UTC, udzura commented on src/timer_thread.c
> +  mrb_value ret = mrb_hash_new_capa(mrb, 2);
yeah

2017-03-25 07:26 UTC, udzura commented on src/timer_thread.c
> +    mrb_sys_fail(mrb, "mrb_get_args");
I see!

2017-03-25 07:29 UTC, matsumotory commented on test/posix_test.rb
> +      usleep 1000
Thanks, I understood. Please add the docs to readme.

2017-03-25 07:35 UTC, matsumotory commented
multiple timer means have multiple Timer::Posix instance in the same code. timer_create sometimes was used for such purposes.

I think top self have realtime signal key as instance variable is data race.

2017-03-27 04:52 UTC, udzura commented
> top self have realtime signal key as instance variable is data race

That sounds reasonable.

I want to remove handler code block support in Timer::POSIX class itself and delegete block registration to [mruby-signal-thread](https://github.com/pyama86/mruby-signal-thread/pull/3). How about this?

2017-03-27 07:40 UTC, udzura commented
>  run multiple timers

Done via https://github.com/matsumotory/mruby-timer-thread/pull/2/commits/865a5a33ae0f8f19372f3fb2e68d580331a3b0c1

2017-03-27 08:09 UTC, matsumotory commented on Rakefile
> +end
Wow, very useful!

2017-03-27 08:21 UTC, matsumotory requested changes
I pointed out a few things, but once these are resolved I will merge!

2017-03-27 08:21 UTC, matsumotory commented on src/timer_thread.c
> +      mrb_raise(mrb, E_ARGUMENT_ERROR, "bad signal");
It is better to unify it to either `if (hoge) fuga;` or `if (hoge) { fuga; }` notation.

2017-03-27 08:21 UTC, matsumotory commented on src/timer_thread.c
> +  }
It is better to unify it to either `if (hoge) fuga;` or `if (hoge) { fuga; }` notation.

2017-03-27 08:23 UTC, matsumotory commented
@udzura  Thank you for your great works! I added you to collaborators! Please check the invited e-mail.

2017-03-27 08:32 UTC, udzura commented
Thanks! I got invitation 💪 

I'm going to fix `if`'s unification!

2017-03-27 09:31 UTC, matsumotory approved these changes

2017-03-27 09:32 UTC, merged

2017-03-27 09:34 UTC, matsumotory commented
Thanks!